version: 0.2

env:
  variables:
    CLUSTER_NAME: three-tier-cluster
    REGION: us-east-1
    ACCOUNT_ID: 207567798584
    FRONTEND_REPO: 3-tier-frontend
    BACKEND_REPO: 3-tier-backend
    IMAGE_TAG: v1.$CODEBUILD_BUILD_NUMBER

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - echo Updating kubeconfig for cluster...
      - aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME

  build:
    commands:
      - echo Building frontend Docker image...
      - docker build -t $FRONTEND_REPO:$IMAGE_TAG ./frontend
      - docker tag $FRONTEND_REPO:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG
      - echo Building backend Docker image...
      - docker build -t $BACKEND_REPO:$IMAGE_TAG ./backend
      - docker tag $BACKEND_REPO:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing frontend image to ECR...
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG
      - echo Pushing backend image to ECR...
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG

      - echo Substituting image tags in manifests...
      - sed -i "s|IMAGE_PLACEHOLDER_FRONTEND|$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG|g" k8s_manifests/frontend-deployment.yaml
      - sed -i "s|IMAGE_PLACEHOLDER_BACKEND|$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG|g" k8s_manifests/backend-deployment.yaml

      - echo Applying all Kubernetes manifests...
      - kubectl apply -f k8s_manifests/mongo/
      - kubectl apply -f k8s_manifests/backend-deployment.yaml
      - kubectl apply -f k8s_manifests/backend-service.yaml
      - kubectl apply -f k8s_manifests/frontend-deployment.yaml
      - kubectl apply -f k8s_manifests/frontend-service.yaml
      - kubectl apply -f k8s_manifests/full_stack_lb.yaml

artifacts:
  files:
    - '**/*'
